### ISSUE TITLE
Maybe need an update in code

### ISSUE THREAD

**Issue by mykeehu** [rsxdalv/extension_f5_tts#2]
I tried the Hungarian model yesterday and failed to generate sound because I got this error:

```
Traceback (most recent call last):
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\queueing.py", line 622, in process_events
response = await route_utils.call_process_api(
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\route_utils.py", line 323, in call_process_api
output = await app.get_blocks().process_api(
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 2014, in process_api
result = await self.call_function(
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\blocks.py", line 1567, in call_function
prediction = await anyio.to_thread.run_sync( # type: ignore
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
return await get_async_backend().run_sync_in_worker_thread(
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio_backends_asyncio.py", line 2177, in run_sync_in_worker_thread
return await future
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\anyio_backends_asyncio.py", line 859, in run
result = context.run(func, *args)
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\gradio\utils.py", line 846, in wrapper
response = f(*args, **kwargs)
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\extension_f5_tts\gradio_app.py", line 94, in infer
ema_model = get_F5TTS_model()
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\extension_f5_tts\gradio_app.py", line 75, in get_F5TTS_model
F5TTS_ema_model = load_model(
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\f5_tts\model\utils_infer.py", line 135, in load_model
model = load_checkpoint(model, ckpt_path, device, use_ema=use_ema)
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\f5_tts\model\utils.py", line 616, in load_checkpoint
model.load_state_dict(checkpoint["model_state_dict"])
File "I:\tts-generation-webui\tts-generation-webui-main\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 2189, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for CFM:
Missing key(s) in state_dict: "mel_spec.mel_stft.spectrogram.window", "mel_spec.mel_stft.mel_scale.fb".
```

[I also spoke to the maker of the model](https://huggingface.co/sarpba/F5-TTS-Hun/discussions/1), and it seems that an update of the extension would be necessary, because the [F5-TTS has been modified](https://github.com/SWivid/F5-TTS) in the meantime. However, with the newer version, the Hungarian model should work (after the vocab replacement).
I just wanted to let you know that things have changed, I'll wait until you have time to make the changes.

**Comment by rsxdalv** [comment]
The plugin has been updated, I forgot to go back to this issue. Now it allows using custom models from huggingface as well. Sorry for the late update.
